In [8]:
import os

from seml import get_results
import matplotlib.pyplot as plt
import torch
import pandas as pd
import numpy as np

import seaborn as sns

In [9]:
df = get_results('dp_timeseries_eval_pld_deterministic_epoch_length',
                 fields=['config.privacy_loss_kwargs.num_sequences',
                         'config.privacy_loss_kwargs.min_sequence_length',
                         'config.privacy_loss_kwargs.batch_size',
                         'config.privacy_loss_kwargs.instances_per_sequence',
                         'result.log_dir'],
            to_data_frame=True,
            filter_dict={
                    'config.privacy_loss_kwargs.bottom_level_mode': 'sampling_with_replacement',
                    'config.privacy_loss_kwargs.top_level_mode': 'iteration',
                    'config.privacy_loss_kwargs.future_length': 1
                })

df = df.drop(columns=['_id'])

df

/nfs/staff-ssd/schuchaj/miniconda3/envs/timeseries_dp/lib/python3.11/site-packag
es/rich/live.py:231: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

config.privacy_loss_kwargs.num_sequences  \
0                                        320   
1                                        320   
2                                        320   
3                                        320   
4                                        320   
5                                        320   
6                                        320   
7                                        320   
8                                        320   
9                                        320   
10                                       320   
11                                       320   
12                                       320   
13                                       320   
14                                       320   
15                                       320   
16                                       320   
17                                       320   
18                                       320   
19                                       320   
20                                       320   
21                                       320   
22                                       320   
23                                       320   
24                                       320   
25                                       320   
26                                       320   
27                                       320   
28                                       320   
29                                       320   
30                                       320   
31                                       320   
32                                       320   
33                                       320   
34                                       320   
35                                       320   
36                                       320   
37                                       320   
38                                       320   
39                                       320   
40                                       320   
41                                       320   
42                                       320   
43                                       320   
44                                       320   

    config.privacy_loss_kwargs.min_sequence_length  \
0                                                2   
1                                                2   
2                                                2   
3                                                2   
4                                                2   
5                                                4   
6                                                4   
7                                                4   
8                                                4   
9                                                4   
10                                              20   
11                                              20   
12                                              20   
13                                              20   
14                                              20   
15                                               2   
16                                               2   
17                                               2   
18                                               2   
19                                               2   
20                                               4   
21                                               4   
22                                               4   
23                                               4   
24                                               4   
25                                              20   
26                                              20   
27                                              20   
28                                              20   
29                                              20   
30                                               2   
31                                               2   
32           

In [10]:
columns = df.columns

df = df.rename(columns={
    c: c.split('.')[-1]
    for c in columns
})

In [11]:
def epsilons_deltas_from_log_dir(df):
    data_dict = {
        'epsilons': [],
        'deltas': []}

    for log_dir in df['log_dir']:
        
        save_dict = torch.load(os.path.join(log_dir, 'config_and_results.pyt'))
        data_dict['epsilons'].append(save_dict['results']['epsilons'])
        data_dict['deltas'].append(save_dict['results']['deltas'])
    
    return pd.DataFrame(data_dict)

In [12]:
df_results = pd.concat((df, epsilons_deltas_from_log_dir(df)), axis=1)
df_results

/tmp/ipykernel_2277978/3179860398.py:8: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  save_dict = torch.load(os.path.join(log_dir, 'config_and_results.pyt'))


num_sequences  min_sequence_length  instances_per_sequence  batch_size  \
0             320                    2                       1          32   
1             320                    2                       2          32   
2             320                    2                       4          32   
3             320                    2                       8          32   
4             320                    2                      16          32   
5             320                    4                       1          32   
6             320                    4                       2          32   
7             320                    4                       4          32   
8             320                    4                       8          32   
9             320                    4                      16          32   
10            320                   20                       1          32   
11            320                   20                       2          32   
12            320                   20                       4          32   
13            320                   20                       8          32   
14            320                   20                      16          32   
15            320                    2                       1         160   
16            320                    2                       2         160   
17            320                    2                       4         160   
18            320                    2                       8         160   
19            320                    2                      16         160   
20            320                    4                       1         160   
21            320                    4                       2         160   
22            320                    4                       4         160   
23            320                    4                       8         160   
24            320                    4                      16         160   
25            320                   20                       1         160   
26            320                   20                       2         160   
27            320                   20                       4         160   
28            320                   20                       8         160   
29            320                   20                      16         160   
30            320                    2                       1         320   
31            320                    2                       2         320   
32            320                    2                       4         320   
33            320                    2                       8         320   
34            320                    2                      16         320   
35            320                    4                       1         320   
36            320                    4                       2         320   
37            320                    4                       4         320   
38            320                    4                       8         320   
39            320                    4                      16         320   
40            320                   20                       1         320   
41            320                   20                       2         320   
42            320                   20                       4         320   
43            320                   20                       8         320   
44            320                   20                      16         320   

                                              log_dir  \
0   /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/...   
1   /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/...   
2   /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/...   
3   /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/...   
4   /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/...   
5   /ceph/hdd/staff/schuchaj/dp_timeseries/icml25/...   
6   /ceph/hdd/st

In [13]:
def plot_tradeoff(df, min_sequence_length, batch_size, epsilon, xlim=None, markersize=4):
    df = df.copy()

    df = df.loc[(df['min_sequence_length'] == min_sequence_length) &
                (df['batch_size'] == batch_size)]

    df = df[['num_sequences', 'batch_size', 'instances_per_sequence', 'epsilons', 'deltas']]
    df = df.sort_values('instances_per_sequence')

    sns.set_theme()
    pal = sns.color_palette('colorblind', 5)

    fig, ax = plt.subplots(1,1)
    
    for i, (_, (num_sequences, batch_size, instances_per_sequence, epsilons, deltas)) in enumerate(df.iterrows()):
        assert (num_sequences % batch_size) == 0

        steps_per_epoch = instances_per_sequence * (num_sequences // batch_size)

        assert epsilons.min() < epsilon < epsilons.max()
        epsilon_index = np.abs(epsilons - epsilon).argmin()
        print(np.abs(epsilons[epsilon_index] - epsilon))

        deltas = deltas[:, epsilon_index]
        deltas = np.insert(deltas, 0, 0)
        print(len(deltas))

        steps = np.arange(1, steps_per_epoch * len(deltas) + 1, steps_per_epoch)

        marker = 'v' if (instances_per_sequence == 1) else '^'

        plt.plot(steps - 1,
                 deltas,
                 linestyle='None',
                 marker=marker,
                 markersize=4,
                 color=pal[i],
                 zorder=3, clip_on=False)
        
        # Dummy line for legend
        plt.plot([],
                 [],
                 label=f'{instances_per_sequence}',
                 linestyle='solid',
                 markersize=markersize,
                 color=pal[i],
                 zorder=3, clip_on=False)
        
        print(steps)

    ax.set_ylim(0, 1.0)
    ax.set_xlim(0, steps[-1] - 1)

    legend_1 = ax.legend(title='$\lambda$', title_fontsize=10, loc='upper left')

    markers = ['v', '^']
    labels = ['Tight upper bound', 'Lower bound']
    dummy_lines = []
    for marker, label in zip(markers, labels):
        dummy_lines.append(ax.scatter([],[], c="black", marker=marker))
    ax.legend(dummy_lines, labels)

    # Add old legend back
    ax.add_artist(legend_1)
    
    ax.set_xticks(ticks=[0, 4, 8, 12, 16])

    ax.set_xlabel('Training step')
    ax.set_ylabel('$\delta(\epsilon)$')

In [14]:
min_sequence_lengths = [4, 20, 4, 20]
batch_sizes = [320, 320, 320, 320]
epsilons = [1.0, 1.0, 4.0, 4.0]

save_dir = '/ceph/hdd/staff/schuchaj/dp_timeseries_plots_camera_icml25/eval_pld_deterministic_epoch_length'

for min_sequence_length, batch_size, epsilon in zip(min_sequence_lengths, batch_sizes, epsilons):

    plot_tradeoff(df_results, min_sequence_length, batch_size, epsilon, xlim=100)


9.992007221626409e-16
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
9.992007221626409e-16
9
[ 1  3  5  7  9 11 13 15 17]
9.992007221626409e-16
5
[ 1  5  9 13 17]
9.992007221626409e-16
3
[ 1  9 17]
9.992007221626409e-16
2
[ 1 17]
9.992007221626409e-16
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
9.992007221626409e-16
9
[ 1  3  5  7  9 11 13 15 17]
9.992007221626409e-16
5
[ 1  5  9 13 17]
9.992007221626409e-16
3
[ 1  9 17]
9.992007221626409e-16
2
[ 1 17]
9.992007221626409e-16
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
9.992007221626409e-16
9
[ 1  3  5  7  9 11 13 15 17]
9.992007221626409e-16
5
[ 1  5  9 13 17]
9.992007221626409e-16
3
[ 1  9 17]
9.992007221626409e-16
2
[ 1 17]
9.992007221626409e-16
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
9.992007221626409e-16
9
[ 1  3  5  7  9 11 13 15 17]
9.992007221626409e-16
5
[ 1  5  9 13 17]
9.992007221626409e-16
3
[ 1  9 17]
9.992007221626409e-16
2
[ 1 17]
0.00036851046124652953
17
[ 1  2  3  4  5  6

In [15]:
min_sequence_lengths = [4, 20, 4, 20]
batch_sizes = [320, 320, 320, 320]
epsilons = [1.0, 1.0, 4.0, 4.0]

save_dir = '/ceph/hdd/staff/schuchaj/dp_timeseries_plots_camera_icml25/eval_pld_deterministic_epoch_length'

for min_sequence_length, batch_size, epsilon in zip(min_sequence_lengths, batch_sizes, epsilons):

    for format in ['png']:
        plot_tradeoff(df_results, min_sequence_length, batch_size, epsilon, xlim=100)
        mplt.savefig(f'{save_dir}/daily_{min_sequence_length}_{batch_size}_{epsilon}', dpi=256, format=format, close_fig='False', preview='png', tight={'pad': 0.5})

9.992007221626409e-16
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
9.992007221626409e-16
9
[ 1  3  5  7  9 11 13 15 17]
9.992007221626409e-16
5
[ 1  5  9 13 17]
9.992007221626409e-16
3
[ 1  9 17]
9.992007221626409e-16
2
[ 1 17]
9.992007221626409e-16
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
9.992007221626409e-16
9
[ 1  3  5  7  9 11 13 15 17]
9.992007221626409e-16
5
[ 1  5  9 13 17]
9.992007221626409e-16
3
[ 1  9 17]
9.992007221626409e-16
2
[ 1 17]
0.00036851046124652953
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
0.00036851046124652953
9
[ 1  3  5  7  9 11 13 15 17]
0.00036851046124652953
5
[ 1  5  9 13 17]
0.00036851046124652953
3
[ 1  9 17]
0.00036851046124652953
2
[ 1 17]
0.00036851046124652953
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
0.00036851046124652953
9
[ 1  3  5  7  9 11 13 15 17]
0.00036851046124652953
5
[ 1  5  9 13 17]
0.00036851046124652953
3
[ 1  9 17]
0.00036851046124652953
2
[ 1 17]
